/* global process, console */
// `pnpm balance:report [--runs 40]` writes docs/BALANCE.md: how careful, random and reckless test
// players fare in each job (endings, weeks, decisions, stress, storylines). Regenerate after content changes.
import { writeFileSync } from 'node:fs';
import { q, run, tail } from './lib/run.mjs';

const i = process.argv.indexOf('--runs');
const runs = i >= 0 ? process.argv[i + 1] : '40';
const sections = [];
for (const scenario of [
  'sales-year',
  'qc-year',
  'fin-year',
  'prod-year',
  'purch-year',
  'inv-year',
  'it-year',
  'mkt-year',
  'fpa-year',
  'sup-year',
  'hr-year',
]) {
  const result = run(
    `npx tsx tools/sim-runner/src/cli.ts balance --scenario ${scenario} --runs ${runs} --content ${q('content')}`,
  );
  if (!result.ok) {
    console.error(tail(result.output));
    process.exit(1);
  }
  sections.push(
    result.output
      .trim()
      .split('\n')
      .filter((l) => !l.startsWith('>'))
      .join('\n'),
  );
}
const doc = `# Balance report

Generated by \`pnpm balance:report\` (${runs} runs per player type, different seeds). Test players:
**careful** always takes c1 (by the book), **reckless** always takes c3 (the shortcut), **random** picks
any choice. Targets: careful players finish (or are promoted) under real but survivable stress;
reckless players are caught before the year ends; about 55 to 70 decisions a year; every storyline
starts in a healthy share of runs. First-cut numbers: the text is an AI first draft and real players
will behave differently.

${sections.join('\n\n')}
`;
writeFileSync('docs/BALANCE.md', doc);
console.log('wrote docs/BALANCE.md');
